function config = earth_moon_orbital_config()
config = struct;
config.simulationName = 'Earth-Moon Orbital Rocket Monte Carlo Simulation';
config.randomSeed = 120826;
config.trialCount = 120;
config.maxSimulationTime_s = 8 * 86400;
config.poweredTimeStep_s = 1;
config.coastTimeStep_s = 60;
config.trajectoryOverviewPoints = 240;
config.progressIntervals = 20;
config.showProgress = true;
config.makeFigures = true;
config.saveFigures = true;
config.figureVisible = 'off';
config.outputDirectoryName = 'results';
config.resultsFileName = 'earth_moon_orbital_results.mat';
config.g0_mps2 = 9.80665;
config.gravitationalConstant = 6.67430e-11;
config.earth = struct;
config.earth.mass_kg = 5.97219e24;
config.earth.radius_m = 6371000;
config.earth.mu_m3ps2 = 3.986004418e14;
config.earth.atmosphereBoundary_m = 120000;
config.earth.referenceDensity_kgpm3 = 1.225;
config.earth.scaleHeight_m = 8500;
config.earth.escapeCheckRadius_m = 250e6;
config.moon = struct;
config.moon.mass_kg = 7.342e22;
config.moon.radius_m = 1737400;
config.moon.orbitalRadius_m = 384400e3;
config.moon.mu_m3ps2 = 4.9048695e12;
config.moon.meanMotion_radps = sqrt(config.earth.mu_m3ps2 / config.moon.orbitalRadius_m ^ 3);
config.moon.orbitalPeriod_s = 2 * pi / config.moon.meanMotion_radps;
config.moon.sphereOfInfluence_m = config.moon.orbitalRadius_m * (config.moon.mass_kg / config.earth.mass_kg) ^ (2 / 5);
config.mission = struct;
config.mission.minimumCaptureDuration_s = 2 * 3600;
config.mission.minimumLunarOrbitDuration_s = 8 * 3600;
config.mission.minimumLunarPeriapses = 1;
config.mission.lunarSuccessDistance_m = config.moon.sphereOfInfluence_m;
config.live = struct;
config.live.defaultTrials = 20;
config.live.frameStride = 10;
config.live.pause_s = 0.001;
config.modelDescription = 'Two-dimensional Earth-centered point-mass launch vehicle model with powered atmospheric ascent, an upper-stage translunar injection impulse above the atmosphere, circular Moon motion, Earth and Moon gravity, exponential atmospheric density, quadratic drag, a randomized lunar insertion impulse at SOI entry, lunar SOI events, and Moon-relative capture energy.';
config.equations = struct;
config.equations.moonMotion = 'r_moon(t) = a*[cos(n*t + phi), sin(n*t + phi)], n = sqrt(mu_earth/a^3)';
config.equations.gravity = 'a_gravity = -mu_earth*r_earth/|r_earth|^3 - mu_moon*r_moon/|r_moon|^3';
config.equations.density = 'rho(h) = rho0*exp(-h/H)';
config.equations.drag = 'a_drag = -0.5*Cd*A*rho*|v_air|*v_air/mass';
config.equations.captureEnergy = 'epsilon_moon = |v_rel|^2/2 - mu_moon/|r_rel|';
config.equations.lunarInsertion = 'v_after = v_before - delta_v_insertion*v_rel/|v_rel| at first inbound SOI entry';
config.equations.translunarInjection = 'v_after = v_before + delta_v_tli*v_earth/|v_earth| after upper-atmosphere ascent';
config.distributions = struct;
config.distributions.dryMass_kg = [20000, 1800, 16000, 25000];
config.distributions.propellantMass_kg = [300000, 26000, 235000, 370000];
config.distributions.burnRate_kgps = [2850, 230, 2350, 3500];
config.distributions.specificImpulse_s = [345, 7, 330, 360];
config.distributions.engineEfficiency = [1.00, 0.015, 0.95, 1.04];
config.distributions.dragCoefficient = [0.35, 0.06, 0.22, 0.52];
config.distributions.referenceArea_m2 = [10, 1.5, 6, 16];
config.distributions.densityMultiplier = [1.00, 0.07, 0.80, 1.20];
config.distributions.initialSpeed_mps = [5, 4, 0, 25];
config.distributions.turnStart_s = [12, 2.5, 6, 20];
config.distributions.turnDuration_s = [82, 8, 62, 104];
config.distributions.targetPitch_deg = [84.5, 0.8, 82, 87];
config.distributions.launchAzimuthCorrection_deg = [0, 0.4, -1, 1];
config.distributions.moonPhase_deg = [90, 10, 75, 105];
config.distributions.lunarInsertionDeltaV_mps = [12000, 800, 10500, 13500];
config.distributions.translunarInjectionDeltaV_mps = [8000, 100, 7800, 8200];
end
