function config = rocket_monte_carlo_config()
config = struct;
config.simulationName = 'Monte Carlo Rocket Trajectory and Flight-Performance Simulation';
config.randomSeed = 120826;
config.launchCount = 100000;
config.timeStep_s = 0.10;
config.maxFlightTime_s = 240;
config.trajectorySampleCount = 600;
config.trajectoryPlotCount = 100;
config.progressIntervals = 20;
config.showProgress = true;
config.makeFigures = true;
config.saveFigures = true;
config.figureVisible = 'off';
config.openResultsOnCompletion = true;
config.openFigureDashboardOnCompletion = true;
config.liveVisualization = false;
config.liveAutoStart = false;
config.liveFrameInterval_s = 0.04;
config.liveDefaultTrials = config.launchCount;
config.liveHistoryDecimation = 1;
config.liveTrajectoryOverviewPoints = 80;
config.liveCompletedRefreshInterval = 100;
config.liveResultsFileName = 'rocket_monte_carlo_live_results.mat';
config.outputDirectoryName = 'results';
config.g0_mps2 = 9.80665;
config.earthRadius_m = 6371000;
config.initialAltitude_m = 1.0;
config.referenceDensity_kgpm3 = 1.225;
config.nominalScaleHeight_m = 8500;
config.nominalTemperature_K = 288.15;
config.speedOfSound_mps = 340.3;
config.mission.minApogee_m = 3500;
config.mission.maxApogee_m = 18000;
config.mission.minRange_m = 500;
config.mission.maxRange_m = 12000;
config.mission.maxDynamicPressure_Pa = 60000;
config.mission.maxAcceleration_mps2 = 15 * config.g0_mps2;
config.modelDescription = 'Two-dimensional point-mass rocket model with constant attitude during powered flight, exponential atmosphere, altitude-varying gravity, steady horizontal wind, thrust-driven propellant depletion, and quadratic aerodynamic drag.';
config.equations = struct;
config.equations.massFlow = 'm_dot = burn_rate';
config.equations.thrust = 'T = m_dot * Isp * g0 * engine_efficiency while propellant remains';
config.equations.drag = 'D_vector = -0.5 * rho * Cd * A * |v_air| * v_air';
config.equations.density = 'rho = rho0 * density_multiplier * (T0 / temperature) * exp(-altitude / scale_height)';
config.equations.gravity = 'g = g0 * (R_earth / (R_earth + altitude))^2';
config.equations.motion = 'a = (T_vector + D_vector) / mass + [0, -g]';
config.distributions = struct;
config.distributions.launchAngle_deg = [78.0, 4.0, 64.0, 88.0];
config.distributions.initialMass_kg = [65.0, 5.0, 50.0, 82.0];
config.distributions.propellantMass_kg = [17.0, 2.0, 11.0, 24.0];
config.distributions.burnRate_kgps = [0.70, 0.07, 0.48, 0.92];
config.distributions.specificImpulse_s = [225.0, 9.0, 195.0, 252.0];
config.distributions.engineEfficiency = [0.95, 0.035, 0.83, 1.04];
config.distributions.dragCoefficient = [0.48, 0.07, 0.26, 0.78];
config.distributions.referenceArea_m2 = [0.020, 0.0020, 0.013, 0.029];
config.distributions.densityMultiplier = [1.00, 0.085, 0.78, 1.24];
config.distributions.scaleHeight_m = [8500.0, 700.0, 6500.0, 10500.0];
config.distributions.temperature_K = [288.15, 11.0, 255.0, 315.0];
config.distributions.windSpeed_mps = [0.0, 7.0, -24.0, 24.0];
end
